image: node:alpine

stages:
  - install
  - lint-code
  - build
  - deploy


cache:
  key: vitpro
  paths:
    - node_module

job_install:
  stage: install
  tags:
    - pro-cicd
  script:
    - npm install

job_build:
  stage: build
  tags:
    - pro-cicd
  script:
    - npm run build


job_deploy:
  stage: deploy
  image: docker
  tags:
    - pro-cicd
  script:
    - docker build -t h5 .
    - if [ $(docker ps -aq --filter name=h51) ]; then docker rm -f h51;fi
    - docker run -d -p 8020:80 --name h51 h5
    # - if [ $(docker ps -aq --filter name=$APP_CONTAINER_NAME) ]; then docker rm -f $APP_CONTAINER_NAME;fi


job_deploy_oss:
  stage: deploy
  tags: 
    - pro-cicd
  script:
    - wget --no-check-certificate https://gosspublic.alicdn.com/ossutil/1.7.7/ossutil64
    - chmod 755 ossutil64
    - ./ossutil64 config -e ${OSSEndPoint} -i ${OSSAccessKeyID} -k ${OSSAccessKeySecret} -L CH --loglevel debug -c ~/.ossutilconfig
    - ./ossutil64 -c ~/.ossutilconfig cp -r -f dist oss://demo1hzh/
    - echo 'deploy alioss success'


